version: '3.8'

services:
  web:
    build:
      context: ./web-client
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  api:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=gatesOfHeaven
      - DB_PASSWORD=password
      - DB_DATABASE=posthub
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=some-secret-key
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=gatesOfHeaven
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=posthub
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
